### ISSUE TITLE
java.lang.UnsupportedClassVersionError: org/itadaki/bzip2/BZip2InputStream has been compiled by a more recent version of the Java Runtime (class file version 53.0), this version of the Java Runtime only recognizes class file versions up to 52.0

### ISSUE THREAD

**Issue by davidjstudholme** [JamesGallant/Genomics#5]
Running from your Docker container, with this command line

```
root@277ba3f859b8:/home/pegasus# bash Pegasus.sh ./myfiles/ ./myfiles/samples.txt ./pegasus_output/ 4 12 T Staph F
/home/pegasus
```
I get the following error message. I had assumed that the Java Runtime was included in the container; but is that not the case? Do I need to downgrade my Java Runtime?

```
Exception in thread "main" java.lang.UnsupportedClassVersionError: org/itadaki/bzip2/BZip2InputStream has been compiled by a more recent version of the Java Runtime (class file version 53.0), this version of the Java Runtime only recognizes class file versions up to 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:757)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:419)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:352)
	at uk.ac.babraham.FastQC.Sequence.SequenceFactory.getSequenceFile(SequenceFactory.java:103)
	at uk.ac.babraham.FastQC.Sequence.SequenceFactory.getSequenceFile(SequenceFactory.java:62)
	at uk.ac.babraham.FastQC.Analysis.OfflineRunner.processFile(OfflineRunner.java:129)
	at uk.ac.babraham.FastQC.Analysis.OfflineRunner.<init>(OfflineRunner.java:102)
	at uk.ac.babraham.FastQC.FastQCApplication.main(FastQCApplication.java:316)
Exception in thread "main" java.lang.UnsupportedClassVersionError: org/itadaki/bzip2/BZip2InputStream has been compiled by a more recent version of the Java Runtime (class file version 53.0), this version of the Java Runtime only recognizes class file versions up to 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:757)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:419)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:352)
	at uk.ac.babraham.FastQC.Sequence.SequenceFactory.getSequenceFile(SequenceFactory.java:103)
	at uk.ac.babraham.FastQC.Sequence.SequenceFactory.getSequenceFile(SequenceFactory.java:62)
	at uk.ac.babraham.FastQC.Analysis.OfflineRunner.processFile(OfflineRunner.java:129)
	at uk.ac.babraham.FastQC.Analysis.OfflineRunner.<init>(OfflineRunner.java:102)
	at uk.ac.babraham.FastQC.FastQCApplication.main(FastQCApplication.java:316)
```

Thanks,

David

**Comment by JamesGallant** [comment]
Hi David, 

Sorry I only saw this today. This is due to discrepancy between some of the dependencies and the java runtime. Thank you for bringing it to my attention. I did indeed configure a java runtime within the container its self but apparently that did not work. I'll have a look and get back to you

**Comment by davidjstudholme** [comment]
Thanks, James.

Just in case it is helpful, this is my java environment within the Docker container:

```
root@52a22b1eaa93:/home/pegasus# java -version
openjdk version "1.8.0_242"
OpenJDK Runtime Environment (build 1.8.0_242-8u242-b08-0ubuntu3~18.04-b08)
OpenJDK 64-Bit Server VM (build 25.242-b08, mixed mode)
```

Best wishes,

David

**Comment by JamesGallant** [comment]
Hi David, 

Again sorry it took so long to look at what was actually a easy fix, I have been preoccupied with finishing up my PhD. So upon inspection of the container the error occurs with fastqc within the container. Performing the QC is more useful when running this outside of a container to inspect the quality of the reads before and after trimming. However, trimming will be done regardless and thus the fastqc is not necessary. I removed it from the containerised environment and drafted a new release. I also pushed the new container to dockerhub. I tested the container with some files I had lying around and it ran without this error. 

Thank you for bringing this to my attention. I'll close the issue now, if you run into any problems please let me know. 

All the best, 
James

**Comment by davidjstudholme** [comment]
Thank you very much indeed for dealing with this, James. I am currently running it against some Staphylococcus data and it seems to be running fine. Fingers crossed ….

Best wishes,

David
